<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <ProjectReference Include="..\WinShield.Domain\WinShield.Domain.csproj" />
    <ProjectReference Include="..\WinShield.Security.Engine\WinShield.Security.Engine.csproj" />
    <ProjectReference Include="..\WinShield.Cleaning.Engine\WinShield.Cleaning.Engine.csproj" />
  </ItemGroup>
</Project>
